import { SPECIES, restore, adopt, tick, clean } from './game.js';
import { Aquarium } from './scene3d.js';
import { drawFishPreview } from './fish3d.js';
const style=document.createElement('link');style.rel='stylesheet';style.href='./src/style.css';document.head.append(style);
const icons={fish:'<path d="M18 12c-5-9-13-7-16 0 3 7 11 9 16 0l5-5v10z"/><circle cx="7" cy="11" r=".6"/>',drop:'<path d="M12 3C9 8 5 11 5 15a7 7 0 0 0 14 0c0-4-4-7-7-12Z"/><path d="M8 15a4 4 0 0 0 4 4"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',food:'<path d="m8 3 8 0 2 5-1 13H7L6 8zM6 8h12"/><circle cx="11" cy="13" r="1"/><circle cx="14" cy="17" r="1"/>',plant:'<path d="M12 22V9M12 14C3 14 3 7 3 7s9-1 9 7Zm0-5c0-8 8-8 8-8s1 8-8 8Zm0 10c0-8 8-8 8-8s1 8-8 8Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m8 4 12 8-12 8z"/>',volume:'<path d="m3 9 5 0 5-5v16l-5-5H3zM17 8c3 3 3 5 0 8m3-11c5 5 5 9 0 14"/>',expand:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>',check:'<path d="m5 12 4 4L20 5"/>',book:'<path d="M12 5C8 2 3 3 2 4v16c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-2-7-2-10 1Zm0 0v16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.fish}</svg>`;
let storageOK=true;let raw=null;try{raw=localStorage.getItem('yeoul-v1');}catch{storageOK=false;}
const state=restore(raw);let paused=false,feedMode=false,sound=false,view='tank',selected=null,audio;
document.body.innerHTML=`
<header class="topbar"><a class="brand" href="./" aria-label="여울 홈"><span class="brand-mark">≈</span><strong>여울<span>YEOUL</span></strong></a><nav aria-label="주 메뉴"><button class="nav active" data-view="tank">나의 어항</button><button class="nav" data-view="collection">물고기 도감</button><button class="nav" data-view="guide">돌봄 가이드</button></nav><div class="top-right"><span class="save-status">${icon('check')} 자동 저장 중</span><button class="coin" id="wallet" title="건강한 물고기가 30초마다 코인을 선물해요"><span>◈</span> <b id="coins">320</b></button></div></header>
<main><section class="heading"><div><p class="eyebrow">A LITTLE WORLD, ALL YOURS</p><h1>작은 물속의 일상<span>.</span></h1><p class="subtitle">천천히 바라보고, 다정하게 돌봐주세요.</p></div><div class="day"><span class="live-dot"></span> <span id="day">DAY 01</span><small>우리의 첫 번째 물결</small></div></section>
<div class="layout"><section class="aquarium-area"><div class="aquarium" id="aquarium"><canvas id="scene" aria-label="열대어가 헤엄치는 어항. 먹이 주기를 선택한 뒤 어항을 클릭하세요."></canvas><div class="scene-top"><div><span class="live-dot"></span> 여울의 어항 <span class="scene-tag">TROPICAL</span></div><button id="fullscreen" class="glass-icon" aria-label="어항 전체 화면">${icon('expand')}</button></div><div class="scene-caption"><span class="tiny-label">SLOW DOWN. LOOK CLOSER.</span><p>물결 사이, 작은 쉼.</p></div><div class="scene-bottom"><span id="scene-hint">드래그로 둘러보기 · 스크롤로 확대 · 물고기 클릭</span><div><button class="glass-icon" id="sound" aria-label="물소리 켜기" aria-pressed="false">${icon('volume')}</button><button class="glass-icon" id="pause" aria-label="일시 정지" aria-pressed="false">${icon('pause')}</button></div></div><div class="fish-info" id="fish-info" hidden></div></div>
<div class="toolbar"><div class="tools"><button class="tool" id="feed">${icon('food')}<span>먹이 주기<small>클릭해서 톡톡</small></span><kbd>F</kbd></button><span class="divider"></span><button class="tool" id="clean">${icon('drop')}<span>물 갈아주기<small>20 코인</small></span></button><span class="divider"></span><button class="tool" id="decorate">${icon('plant')}<span>수초 심기<small>40 코인</small></span></button></div><button class="light-toggle" id="light" aria-pressed="true">${icon('sun')}<span>조명</span><i></i></button></div>
<div class="section-line"><h2>함께 사는 친구들 <span id="fish-count">5</span></h2><button id="open-shop">새 친구 데려오기 <span>＋</span></button></div><div class="residents" id="residents"></div></section>
<aside><section class="care panel"><div class="panel-title"><h2>오늘의 어항</h2><span class="status-pill" id="overall">아주 평온해요</span></div><div class="temperature"><span>26<sup>°C</sup></span><div>포근한 수온<small>열대어가 좋아하는 온도</small></div>${icon('sun')}</div><div id="meters"></div><p class="care-note" id="care-note">좋은 물, 행복한 물고기.<br>지금처럼만 돌봐주세요.</p></section>
<section class="mission panel"><div class="panel-title"><h2>작은 돌봄 일지</h2><span class="outline-icon">${icon('book')}</span></div><p class="muted">작은 관심이 큰 행복이 돼요.</p><div id="missions"></div></section>
<section class="quote"><span>“</span><p>서두르지 않아도 괜찮아요.<br>여기서는 모든 것이<br>자기만의 속도로 자라니까요.</p><small>A MOMENT OF BLUE</small></section></aside></div><footer><span>여울 <i>작은 생명과 함께 흐르는 시간</i></span><span>코드로 빚은, 하나뿐인 물속 세상</span></footer></main>
<dialog id="modal"><div class="modal-top"><div><p class="eyebrow" id="modal-label">A NEW LITTLE FRIEND</p><h2 id="modal-title"></h2></div><button id="close-modal" class="icon-button" aria-label="닫기">${icon('close')}</button></div><div id="modal-content"></div></dialog><div id="toast" role="status" aria-live="polite"></div>`;
const $=s=>document.querySelector(s);const scene=new Aquarium($('#scene'),state,()=>{},()=>update());
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function save(){try{localStorage.setItem('yeoul-v1',JSON.stringify(state));$('.save-status').innerHTML=icon('check')+' 저장 완료';}catch{storageOK=false;$('.save-status').textContent='저장 공간을 사용할 수 없어요';}}
function miniFish(canvas,type){drawFishPreview(canvas,type);}
function residentCards(){ $('#residents').innerHTML=SPECIES.map((sp,type)=>{const count=state.fish.filter(f=>f.type===type).length;return `<button class="resident" data-species="${type}"><span class="resident-count">${count} 마리</span><canvas aria-hidden="true"></canvas><div><strong>${sp.name}</strong><span>${count?'함께 헤엄치는 중':'새로운 만남을 기다려요'}</span></div><span class="card-arrow">↗</span></button>`;}).join(''); document.querySelectorAll('.resident').forEach(el=>{miniFish(el.querySelector('canvas'),+el.dataset.species);el.onclick=()=>showSpecies(+el.dataset.species);}); }
const missions=[{id:'feed',label:'친구들에게 먹이 주기',goal:5,reward:30,get:()=>state.fed},{id:'clean',label:'깨끗한 물 선물하기',goal:1,reward:40,get:()=>state.cleaned},{id:'grow',label:'한 친구 성장도 20% 달성',goal:20,reward:80,get:()=>Math.max(...state.fish.map(f=>f.growth))}];
function update(){const hunger=state.fish.reduce((s,f)=>s+f.hunger,0)/state.fish.length;$('#coins').textContent=state.coins.toLocaleString();$('#fish-count').textContent=state.fish.length;$('#day').textContent=`DAY ${String(1+Math.floor(state.elapsed/600)).padStart(2,'0')}`;
$('#meters').innerHTML=[['수질',state.quality,'맑고 깨끗해요'],['산소',state.oxygen,'숨쉬기 편안해요'],['포만감',hunger,'배부르고 든든해요']].map(([label,value,good])=>`<div class="metric"><div><span>${label}</span><b>${Math.round(value)}<small> / 100</small></b></div><div class="track"><i style="width:${value}%;background:${value<35?'#bd8860':'#59847a'}"></i></div><small>${value<35?'돌봄이 필요해요':good}</small></div>`).join('');
const low=Math.min(state.quality,state.oxygen,hunger)<35;$('#overall').textContent=low?'관심이 필요해요':'아주 평온해요';$('#care-note').innerHTML=low?'먹이와 수질을 확인해주세요.<br>작은 돌봄으로 다시 건강해져요.':'좋은 물, 행복한 물고기.<br>지금처럼만 돌봐주세요.';
$('#missions').innerHTML=missions.map(m=>{const done=state.claimed.includes(m.id),ready=m.get()>=m.goal;return `<button class="mission-row ${done?'done':''}" data-mission="${m.id}" ${!ready||done?'disabled':''}><span class="mission-check">${done?icon('check'):''}</span><span>${m.label}<small>${done?'선물 받기 완료':ready?'눌러서 선물 받기':`${Math.min(m.goal,Math.floor(m.get()))} / ${m.goal}`}</small></span><b>${done?'✓':'+'+m.reward}</b></button>`;}).join('');
document.querySelectorAll('[data-mission]').forEach(el=>el.onclick=()=>{const m=missions.find(m=>m.id===el.dataset.mission);if(m.get()>=m.goal&&!state.claimed.includes(m.id)){state.claimed.push(m.id);state.coins+=m.reward;notify(`${m.reward} 코인을 선물로 받았어요.`);update();save();}});
$('#light').setAttribute('aria-pressed',state.light);$('#light').classList.toggle('off',!state.light);if(selected)showFishInfo();}
function showFishInfo(){const f=state.fish.find(f=>f.id===selected);if(!f)return;$('#fish-info').hidden=false;$('#fish-info').innerHTML=`<strong>${f.name}</strong><span>성장 ${Math.floor(f.growth)}% · 포만감 ${Math.round(f.hunger)}%</span><small>${f.growth>=100?'다 자란 어른 물고기':f.hunger<35?'배가 고파요. 먹이를 주세요.':'오늘도 조금씩 자라는 중'}</small>`;}
function openModal(title,label){$('#modal-title').textContent=title;$('#modal-label').textContent=label;$('#modal').showModal();}
function shop(){openModal('새로운 만남을 기다려요','A NEW LITTLE FRIEND');$('#modal-content').innerHTML=`<p class="modal-intro">작은 친구에게 따뜻한 집을 선물하세요. <b>${state.fish.length} / 16 마리</b></p><div class="shop-grid">${SPECIES.map((s,i)=>`<article class="shop-card"><canvas data-preview="${i}" aria-hidden="true"></canvas><h3>${s.name}</h3><small>${s.latin}</small><p>${s.description}</p><button class="primary" data-buy="${i}" ${state.coins<s.price||state.fish.length>=16?'disabled':''}>${state.fish.length>=16?'어항이 가득 찼어요':`입양하기 · ${s.price} ◈`}</button></article>`).join('')}</div><p class="footnote">건강한 친구 한 마리마다 30초에 3 코인을 선물해요.<br>이 게임은 상상 속의 어항이에요. 실제 사육 환경과는 달라요.</p>`;document.querySelectorAll('[data-preview]').forEach(c=>miniFish(c,+c.dataset.preview));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const type=+b.dataset.buy;if(adopt(state,type)){notify(`${SPECIES[type].name}가 새 가족이 되었어요!`);update();residentCards();save();$('#modal').close();}});}
function showSpecies(type){const s=SPECIES[type],fish=state.fish.filter(f=>f.type===type);openModal(s.name,'MEET YOUR LITTLE FRIEND');$('#modal-content').innerHTML=`<div class="species-hero"><canvas id="species-preview"></canvas><p>${s.latin}</p><h3>${s.description}</h3></div><p class="modal-intro">함께 사는 친구 ${fish.length}마리</p>${fish.map(f=>`<div class="fish-detail"><strong>${f.name}</strong><span>포만감 ${Math.round(f.hunger)}% · 성장 ${Math.floor(f.growth)}%</span></div>`).join('')||'<p>아직 이 친구와 만나지 못했어요.</p>'}<button class="primary wide" id="species-adopt">입양 상점 열기</button>`;miniFish($('#species-preview'),type);$('#species-adopt').onclick=()=>{$('#modal').close();shop();};}
function guide(){openModal('천천히, 다정하게 돌보기','A SMALL GUIDE TO CARING');$('#modal-content').innerHTML=`<div class="guide"><h3>01 · 먹이를 톡톡</h3><p>먹이 주기 또는 F 키를 누른 뒤 어항을 클릭하세요. 친구들이 먹이를 따라 헤엄쳐요. 남은 먹이는 수질을 떨어뜨리니 조금씩 주세요.</p><h3>02 · 맑은 물, 푸른 수초</h3><p>20 코인으로 물을 갈면 수질이 35, 산소가 15 올라가요. 수초는 40 코인이며 산소를 공급해요. 최대 12포기까지 심을 수 있어요.</p><h3>03 · 함께 자라는 시간</h3><p>포만감과 수질을 잘 유지하면 물고기가 자라요. 먹이를 먹을 때도 성장해요. 건강한 친구마다 30초에 3 코인을 모아 새 친구를 입양하세요.</p><h3>04 · 나만의 작은 쉼</h3><p>물고기를 클릭해 성장도를 확인하세요. 조명과 물소리를 바꾸거나 Space 키로 쉬어갈 수 있어요. 게임은 이 브라우저에 자동 저장되며 창을 닫은 동안에는 시간이 흐르지 않아요.</p><p class="footnote">수온은 게임에서 26°C로 고정됩니다. 민물·바닷물 물고기를 함께 기르는 상상 속 게임으로, 실제 사육 지침은 아닙니다.</p></div>`;}
$('#open-shop').onclick=shop;$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;if(view==='collection'){openModal('우리의 물고기 도감','THE LITTLE AQUATIC ENCYCLOPEDIA');$('#modal-content').innerHTML=`<div class="collection-grid">${SPECIES.map((s,i)=>`<button class="collection-card" data-collection="${i}"><canvas></canvas><h3>${s.name}</h3><small>${s.latin}</small><p>${state.fish.filter(f=>f.type===i).length} 마리 함께하는 중 ↗</p></button>`).join('')}</div>`;document.querySelectorAll('[data-collection]').forEach(el=>{miniFish(el.querySelector('canvas'),+el.dataset.collection);el.onclick=()=>{$('#modal').close();showSpecies(+el.dataset.collection);};});}else if(view==='guide')guide();else{$('#modal').close();$('#aquarium').scrollIntoView({behavior:'smooth',block:'center'});}});
$('#feed').onclick=()=>{feedMode=!feedMode;scene.controls.enableRotate=!feedMode;$('#feed').classList.toggle('active',feedMode);$('#feed').setAttribute('aria-pressed',feedMode);$('#scene-hint').textContent=feedMode?'먹이를 떨어뜨릴 곳을 클릭하세요 · 다시 F를 누르면 관찰 모드':'드래그로 둘러보기 · 스크롤로 확대 · 물고기 클릭';$('#scene').style.cursor=feedMode?'crosshair':'pointer';};
$('#scene').onclick=e=>{const rect=$('#scene').getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;if(paused){notify('잠시 멈춰 있어요. 재생 버튼을 눌러주세요.');return;}if(feedMode){if(scene.drop(scene.pointAt(x,y).x,scene.pointAt(x,y).z)){notify('먹이가 사르르. 친구들이 모여들어요.');}else notify('아직 먹이가 남아 있어요. 조금 기다려주세요.');}else{const f=scene.hit(x,y);selected=f?.id;scene.selected=selected;$('#fish-info').hidden=!f;if(f)showFishInfo();else scene.ripple(scene.pointAt(x,y).x,.5);}};
$('#clean').onclick=()=>{if(paused){notify('재생 후 돌봐주세요.');return;}if(clean(state)){notify('새 물로 갈아주었어요. 한결 상쾌해요!');update();save();}else notify(state.coins<20?'20 코인이 필요해요.':'이미 물이 아주 깨끗해요.');};
$('#decorate').onclick=()=>{if(state.plants>=12)return notify('수초가 충분히 자라고 있어요.');if(state.coins<40)return notify('40 코인이 필요해요.');state.coins-=40;state.plants++;notify(`새 수초를 심었어요. (${state.plants}/12)`);update();save();};
$('#light').onclick=()=>{state.light=!state.light;update();save();};
$('#pause').onclick=()=>{paused=!paused;$('#pause').innerHTML=icon(paused?'play':'pause');$('#pause').setAttribute('aria-label',paused?'다시 재생':'일시 정지');$('#pause').setAttribute('aria-pressed',paused);notify(paused?'잠시 쉬어가는 중. 시간도 멈춰 있어요.':'다시 물결이 흐르기 시작해요.');};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#aquarium').requestFullscreen();}catch{notify('이 브라우저에서는 전체 화면을 지원하지 않아요.');}};
$('#sound').onclick=async()=>{try{if(!audio){const context=new AudioContext(),buffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.04-.02)/1.02;data[i]=last*2;}const source=context.createBufferSource();source.buffer=buffer;source.loop=true;const filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=600;const gain=context.createGain();gain.gain.value=.16;source.connect(filter).connect(gain).connect(context.destination);source.start();audio=context;}sound=!sound;if(sound)await audio.resume();else await audio.suspend();$('#sound').setAttribute('aria-pressed',sound);$('#sound').setAttribute('aria-label',sound?'물소리 끄기':'물소리 켜기');notify(sound?'잔잔한 물소리를 켰어요.':'물소리를 껐어요.');}catch{notify('물소리를 재생할 수 없어요.');}};
$('#wallet').onclick=()=>notify('건강한 친구마다 30초에 3 코인! 돌봄 일지에서도 선물을 받아보세요.');
document.addEventListener('keydown',e=>{if($('#modal').open||['INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='KeyF')$('#feed').click();if(e.code==='Space'){e.preventDefault();$('#pause').click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();audio?.suspend();}else if(sound)audio?.resume();});window.addEventListener('pagehide',save);
residentCards();update();if(!storageOK)notify('이 브라우저에서는 저장이 제한되어 있어요.');
let last=performance.now(),lastUI=0,lastSave=0;
function frame(now){const dt=Math.min((now-last)/1000,.06);last=now;if(!document.hidden){if(!paused){tick(state,dt);scene.update(dt);}scene.render();if(now-lastUI>1000){update();lastUI=now;}if(now-lastSave>10000){save();lastSave=now;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);

